import "bootstrap/dist/css/bootstrap.min.css"
// import "bootstrap/dist/js/bootstrap.bundle.js"
import "bootstrap-icons/font/bootstrap-icons.css"
import { Inter } from "next/font/google";
import NavComponent from "./components/NavComponent";
import { format } from 'date-fns';
// import './globals.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className={inter.className}>
          <NavComponent />
            {children}
        </main>
      </body>
    </html>
  );
}
